document.write("<h1>Rules for naming JS Varibals</h1>")
document.write("<p>Variable names can only contain,numbers,$ and. For example $my_1stVariable</p>")
document.write("<p>Variables must begin with a letter,$ or_.For example : $name,_name or name</p>")
document.write("<p>Variable names are case sensitive</p>")
document.write("<p>Variable names should not be JS Keywords</p>")